# Generated by Django 5.0.7 on 2024-07-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataObject',
        ),
    ]
